package com.velocity.ivr.model;
// Generated Jan 16, 2011 2:04:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Calldetails generated by hbm2java
 */
public class CallDetails  implements java.io.Serializable {


     private int callId;
     private String calledFrom;
     private String alternateNumber;
     private String name;
     private String address1;
     private String address2;
     private String city;
     private Integer zip;
     private String country;
     private String email;
     private int status;
     private String comments;
     private Date creationTime;
     private Set<CallLog> callLogs = new HashSet<CallLog>(0);

    public CallDetails() {
    }

	
    public CallDetails(int callId, String calledFrom, int status, Date creationTime) {
        this.callId = callId;
        this.calledFrom = calledFrom;
        this.status = status;
        this.creationTime = creationTime;
    }
    public CallDetails(int callid, String calledFrom, String alternateNumber, String name, String address1, String address2, String city, Integer zip, String country, String email, int status, String comments, Date creationtime, Set callLogs) {
       this.callId = callid;
       this.calledFrom = calledFrom;
       this.alternateNumber = alternateNumber;
       this.name = name;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.zip = zip;
       this.country = country;
       this.email = email;
       this.status = status;
       this.comments = comments;
       this.creationTime = creationtime;
       this.callLogs = callLogs;
    }
   
    public int getCallId() {
        return this.callId;
    }
    
    public void setCallId(int callId) {
        this.callId = callId;
    }
    public String getCalledFrom() {
        return this.calledFrom;
    }
    
    public void setCalledFrom(String calledFrom) {
        this.calledFrom = calledFrom;
    }
    public String getAlternateNumber() {
        return this.alternateNumber;
    }
    
    public void setAlternateNumber(String alternateNumber) {
        this.alternateNumber = alternateNumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getZip() {
        return this.zip;
    }
    
    public void setZip(Integer zip) {
        this.zip = zip;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    public Set<CallLog> getCallLogs() {
        return this.callLogs;
    }
    
    public void setCallLogs(Set<CallLog> callLogs) {
        this.callLogs = callLogs;
    }




}


